#' Journal-style colour palettes
#'
#' Discrete palettes matching the house styles of several journals, plus three
#' viridis ramps. Built lazily by a function rather than stored as a package
#' constant so that the viridis colours are generated by the installed version
#' of \pkg{viridisLite} rather than frozen at build time.
#'
#' @return A named list of character vectors, each holding eight hex colours.
#' @export
#' @examples
#' names(publication_palettes())
#' publication_palettes()[["Nature"]]
publication_palettes <- function() {
  list(
    "Nature"    = c("#E64B35", "#4DBBD5", "#00A087", "#3C5488",
                    "#F39B7F", "#8491B4", "#91D1C2", "#DC0000"),
    "Science"   = c("#3B4992", "#EE0000", "#008B45", "#631879",
                    "#008280", "#BB0021", "#5F559B", "#A20056"),
    "Lancet"    = c("#00468B", "#ED0000", "#42B540", "#0099B4",
                    "#925E9F", "#FDAF91", "#AD002A", "#ADB6B6"),
    "JAMA"      = c("#374E55", "#DF8F44", "#00A1D5", "#B24745",
                    "#79AF97", "#6A6599", "#80796B", "#B24745"),
    "NEJM"      = c("#BC3C29", "#0072B5", "#E18727", "#20854E",
                    "#7876B1", "#6F99AD", "#FFDC91", "#EE4C97"),
    "Economist" = c("#6794a7", "#014d64", "#01a2d9", "#7ad2f6",
                    "#00887d", "#76c0c1", "#7c260b", "#ee8f71"),
    "Tableau10" = c("#4E79A7", "#F28E2B", "#E15759", "#76B7B2",
                    "#59A14F", "#EDC948", "#B07AA1", "#FF9DA7"),
    "Okabe-Ito" = c("#E69F00", "#56B4E9", "#009E73", "#F0E442",
                    "#0072B2", "#D55E00", "#CC79A7", "#000000"),
    "Viridis"   = viridisLite::viridis(8),
    "Plasma"    = viridisLite::viridis(8, option = "plasma"),
    "Cividis"   = viridisLite::viridis(8, option = "cividis")
  )
}

#' Look up a palette by name
#'
#' @param name Palette name, see [publication_palettes()].
#' @return Character vector of colours; falls back to `"Nature"` for an
#'   unknown name so that a stale bookmarked input cannot break plotting.
#' @export
get_palette <- function(name) {
  pals <- publication_palettes()
  pals[[name %||% "Nature"]] %||% pals[["Nature"]]
}
